# Generated by Django 3.2.19 on 2025-09-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20250916_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seat',
            name='tier',
            field=models.CharField(choices=[('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver')], default='SILVER', max_length=10),
        ),
    ]
